# Generated by Django 4.1 on 2022-09-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name_plural': 'Галерея товаров'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Отзыв и оценка', 'verbose_name_plural': 'Отзывы и оценки'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Вариация', 'verbose_name_plural': 'Вариации'},
        ),
    ]
